---
model_and_data: RESNET_50
train_structure: cifar10

fit_config:
  net_config: {}
  dataloader_config:
    batch_size: 32
  run_config:
    epochs: 2
    learning_rate: 0.1
  extra: {}

eval_config:
  net_config: {}
  dataloader_config:
    batch_size: 32
  run_config: {}
  extra: {}

fed_test_config:
  net_config: {}
  dataloader_config:
    batch_size: 32
  run_config: {}
  extra: {}

net_config_initial_parameters: {}

fit_metrics: [train_loss, train_accuracy]
evaluate_metrics: [test_accuracy]
